export const dataConstants = {
  GET_PIE_CHART_DATA_REQUEST: 'GET_PIE_CHART_DATA_REQUEST',
  GET_PIE_CHART_DATA_SUCCESS: 'GET_PIE_CHART_DATA_SUCCESS',
  GET_PIE_CHART_DATA_FAILURE: 'GET_PIE_CHART_DATA_FAILURE',

  GET_BAR_CHART_DATA_REQUEST: 'GET_BAR_CHART_DATA_REQUEST',
  GET_BAR_CHART_DATA_SUCCESS: 'GET_BAR_CHART_DATA_SUCCESS',
  GET_BAR_CHART_DATA_FAILURE: 'GET_BAR_CHART_DATA_FAILURE',
};
